# ----
# Site

title: Zynk Workflow Documentation
url: "http://workflow.zynk.com"
baseurl:
google_analytics_key:
show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation for Zynk Workflow.
author:
  name: Adam 
  email: support@zynk.com
  twitter: zynk
social:
  name: Zynk Workflow Docs Template
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-redirect-from

#gems:
 # - github-pages
  #- jekyll-redirect-from


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    #permalink: /:path/
    permalink: /:slug.html
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - minor
  - major
